name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - lib/**
      - .github/workflows/**
      - native/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3.5.2
      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: "zulu"
          java-version: "17"

      - run: echo $ENCODED_KEYSTORE | base64 -di > android/app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Rust & Generate Message
        run: |
          rustup update stable
          cargo install rinf
          rinf message
          dart fix --apply

      - run: flutter build apk --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: armAll
          path: build/app/outputs/apk/release/*

      - run: flutter build apk --split-per-abi --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: apks
          path: build/app/outputs/apk/release/*
