name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - lib/**
      - .github/workflows/**
      - native/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3.5.2
      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Install Rust & Generate Message
        run: |
          rustup update stable
          cargo install rinf
          rinf message

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter build apk --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: armAll
          path: build/app/outputs/apk/release/*

      - run: flutter build apk --split-per-abi --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: apks
          path: build/app/outputs/apk/release/*
